apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminserver
  labels:
    app: adminserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: adminserver
  template:
    metadata:
      labels:
        app: adminserver
    spec:
      containers:
        - name: adminserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}

          env:
            - name: SERVER_PORT
              value: "{{ .Values.containerPort }}"

            - name: MAIL_NOTIFICATIONS_ENABLED
              value: "false"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20

          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m