apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-networking
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ziazeshan141/shopping-portal-gitops.git
    targetRevision: main
    path: infrastructure/networking

  destination:
    server: https://kubernetes.default.svc
    namespace: shopping

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true