apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-monitoring
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 86.0.1

    helm:
      releaseName: shopping-monitoring

      values: |
        grafana:
          enabled: true

          service:
            type: ClusterIP

          persistence:
            enabled: false

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        prometheus:
          enabled: true

          prometheusSpec:
            retention: 7d

            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: "1"
                memory: 1Gi

        alertmanager:
          enabled: true

        kubeEtcd:
          enabled: false

        kubeControllerManager:
          enabled: false

        kubeScheduler:
          enabled: false

        kubeProxy:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true