apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  type: {{ .Values.service.type }}

  selector:
    app: product

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http