replicaCount: 1

image:
  repository: ziazeshan141/shopping-userservice
<<<<<<< HEAD
  tag: "12"
=======
  tag: "13"
>>>>>>> a05a5d289e9ee5735bc9600d18f318434fdcf62f
  pullPolicy: IfNotPresent

containerPort: 9092

service:
  type: ClusterIP
  port: 9092

config:
  dbUrl: jdbc:mysql://mysql:3306/user_management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  dbUsername: root